/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rtpcollege;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.lang.System.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static scala.reflect.internal.util.NoFile.path;
import static scala.reflect.internal.util.NoSourceFile.path;

/**
 *
 * @author Jatin
 */
public class something extends javax.swing.JFrame {
    String path;
    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form something
     */
    public something() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredients_details = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        recipe_details1 = new javax.swing.JTextArea();
        recipe_name = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        gohome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(74, 74, 72));
        jPanel4.setPreferredSize(new java.awt.Dimension(340, 234));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(74, 74, 72));
        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 120));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(168, 192, 192));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingredients");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 349, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 40));

        ingredients_details.setBackground(new java.awt.Color(74, 74, 72));
        ingredients_details.setColumns(20);
        ingredients_details.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingredients_details.setForeground(new java.awt.Color(168, 192, 192));
        ingredients_details.setRows(5);
        ingredients_details.setText("\n");
        ingredients_details.setBorder(null);
        ingredients_details.setSelectionColor(new java.awt.Color(85, 107, 47));
        jScrollPane1.setViewportView(ingredients_details);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 470));

        recipe_details1.setBackground(new java.awt.Color(74, 74, 72));
        recipe_details1.setColumns(20);
        recipe_details1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recipe_details1.setForeground(new java.awt.Color(168, 192, 192));
        recipe_details1.setRows(5);
        recipe_details1.setText("Enter the recipe here->");
        recipe_details1.setBorder(null);
        recipe_details1.setSelectionColor(new java.awt.Color(85, 107, 47));
        jScrollPane3.setViewportView(recipe_details1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 500, 510));

        recipe_name.setBackground(new java.awt.Color(51, 51, 51));
        recipe_name.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        recipe_name.setForeground(new java.awt.Color(168, 192, 192));
        recipe_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        recipe_name.setText("Enter recipe name");
        recipe_name.setToolTipText("");
        recipe_name.setBorder(null);
        jPanel1.add(recipe_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 850, 40));

        search.setBackground(new java.awt.Color(85, 107, 47));
        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(168, 192, 192));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        delete.setText("DELETE");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(168, 192, 192));
        update.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        update.setText("UPDATE");

        insert.setBackground(new java.awt.Color(168, 192, 192));
        insert.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        insert.setText("INSERT");
        insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        gohome.setBackground(new java.awt.Color(168, 192, 192));
        gohome.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        gohome.setText("HOME");
        gohome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gohomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(gohome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(insert)
                    .addComponent(gohome))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 850, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        String Name = null, details = null, query,is = null;
        String Surl, Suser, Spass;
        Surl = "jdbc:MYSQL://localhost:3307/recipe_login";
        Suser = "root";
        Spass = "";
        
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(Surl, Suser, Spass);
                Statement st = connection.createStatement();
                //login_page l1 = new login_page();
                //recipe_email = l1.loginemail;
                if ("".equals(recipe_name.getText())) {
                    JOptionPane.showMessageDialog(new JFrame(), "Please enter email", "Error",
                        JOptionPane.ERROR_MESSAGE);
                } else if ("".equals(recipe_details1.getText())) {
                    JOptionPane.showMessageDialog(new JFrame(), "Please enter email", "Error",
                        JOptionPane.ERROR_MESSAGE);
                } else {
                    Name = recipe_name.getText();
                    details = recipe_details1.getText();
                    is=ingredients_details.getText();
                    // recipe_email = login_page.loginemail.getText();
                    // System.out.print(recipe_email);
                }
                // sql="INSERT INTO recipe(login_id)"+"SELECT id "+"FROM login";
                query = "INSERT INTO recipe(name,details,image)" +
                "VALUES('" + Name + "','" + details + "','" + is + "')";
                //System.out.println(recipe_email);
                // st.execute(sql);
                st.execute(query);
                recipe_name.setText("");

                showMessageDialog(null, "Recipe Inserted");
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println("Error" + e.getMessage());
            }
       
    }//GEN-LAST:event_insertActionPerformed

    private void gohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gohomeActionPerformed
        Home HomeFrame = new Home();
                HomeFrame.setVisible(true);
                HomeFrame.pack();
                HomeFrame.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_gohomeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       String Name = null, details = null, query;
        String Surl, Suser, Spass;
        Surl = "jdbc:MYSQL://localhost:3307/recipe_login";
        Suser = "root";
        Spass = "";
        String id;
        id=recipe_name.getText();
        if(recipe_name==null){
            showMessageDialog(null, "Enter recipename only");
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection(Surl, Suser, Spass);
            Statement st = connection.createStatement();
            String recipe_delete="DELETE FROM recipe WHERE name='"+id+"'";
            st.execute(recipe_delete);
        }
        catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new something().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton gohome;
    private javax.swing.JTextArea ingredients_details;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea recipe_details1;
    private javax.swing.JTextField recipe_name;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
